variables:
  LANG: "C.UTF-8"

.specs: &specs
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - vendor/ruby
  before_script:
    - apt update
    - apt install python-pip git build-essential -y
    - pip install 'docutils==0.13.1'
    - bundle install --jobs $(nproc)
  script:
    - bundle exec rake test

ruby-23:
  image: ruby:2.3
  <<: *specs
ruby-24:
  <<: *specs
  image: ruby:2.4
ruby-25:
  <<: *specs
  image: ruby:2.5
