variables:
  LANG: "C.UTF-8"
  DOCUTILS_VERSION: "0.14"

.specs: &specs
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - vendor/ruby
  before_script:
    - apt update
    - apt install python3 python3-pip git build-essential -y
    - apt remove python -y
    - pip3 install "docutils==$DOCUTILS_VERSION"
    - bundle install --jobs $(nproc)
  script:
    - bundle exec rake test

.docutils-015:
  variables:
    DOCUTILS_VERSION: "0.15.2"
.docutils-016:
  variables:
    DOCUTILS_VERSION: "0.16"

ruby-24:
  image: ruby:2.4
  <<: *specs
ruby-25:
  image: ruby:2.5
  <<: *specs
ruby-26:
  image: ruby:2.6
  <<: *specs
ruby-27:
  image: ruby:2.7
  <<: *specs

ruby-24-du15:
  image: ruby:2.4
  extends: .docutils-015
  <<: *specs
ruby-25-du15:
  image: ruby:2.5
  extends: .docutils-015
  <<: *specs
ruby-26-du15:
  image: ruby:2.6
  extends: .docutils-015
  <<: *specs
ruby-27-du15:
  image: ruby:2.7
  extends: .docutils-015
  <<: *specs

ruby-24-du16:
  image: ruby:2.4
  extends: .docutils-016
  <<: *specs
ruby-25-du16:
  image: ruby:2.5
  extends: .docutils-016
  <<: *specs
ruby-26-du16:
  image: ruby:2.6
  extends: .docutils-016
  <<: *specs
ruby-27-du16:
  image: ruby:2.7
  extends: .docutils-016
  <<: *specs
